api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]

        framework:
            form: { enabled: true }
         api_platform:
            enable_fos_user: true
