# config/packages/vich_uploader.yaml or app/config/config.yml
vich_uploader:
    db_driver: orm

    mappings:
        users_image:
            uri_prefix: /images/users
            upload_destination: '%kernel.project_dir%/public/images/uses'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer