vich_uploader:
    db_driver: orm


mappings :
         users_image :
             uri_prefix : / photo/ users 
            upload_destination : ' % kernel.project_dir% / public / photo / userss '
             namer : Vich \ UploaderBundle \ Naming \ SmartUniqueNamer

             inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
